name: firefit_mobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_svg: ^2.0.7
  geolocator: ^12.0.0
  google_maps_flutter: ^2.5.0
  permission_handler: 11.3.1
  firebase_core: ^2.28.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.2.0
  cloud_firestore: ^4.12.0
  image_picker: ^1.0.4
  video_player: ^2.8.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  sensors_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  path_provider: ^2.1.5
  gal: ^2.3.2
  pdf: ^3.11.3
  open_filex: ^4.3.4
  printing: ^5.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/logo.svg
    - assets/images/app_logo.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.png"

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf